"""AI 생성물 표시 — 「인공지능 발전과 신뢰 기반 조성 등에 관한 기본법」(2026-01-22 시행).

법은 생성형 AI 산출물에 대해 ①사람이 인식 가능한 방식 또는 ②기계 판독 가능한
방식의 표시를 요구한다. 증명사진은 가시 워터마크를 넣으면 용도가 사라지므로
기계 판독 표시(메타데이터)가 현실적인 경로이며, **그 조합이 적법한지는
법률 자문으로 확정해야 한다**(docs/fact-check.md 참조).

여기서는 두 가지를 구현한다:
  1. EXIF/XMP 메타데이터 — IPTC DigitalSourceType = trainedAlgorithmicMedia
  2. 프리뷰용 가시 워터마크 — 무료 체험·미리보기에만 적용

C2PA Content Credentials 는 서명 인증서가 필요해 여기서는 다루지 않는다.
프로덕션에서는 c2pa-python 등으로 서명을 붙일 것.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

import cv2
import numpy as np

#: IPTC DigitalSourceType 어휘 — AI 전면 생성물
TRAINED_ALGORITHMIC_MEDIA = (
    "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia")

DISCLOSURE_KO = "이 이미지는 인공지능으로 생성되었습니다."
DISCLOSURE_EN = "This image was generated by artificial intelligence."


def disclosure_record(*, provider: str, model: str, spec: str,
                      preset: dict | None = None,
                      order_id: str | None = None) -> dict:
    """감사 로그와 메타데이터에 함께 쓰는 표준 레코드."""
    return {
        "ai_generated": True,
        "digital_source_type": TRAINED_ALGORITHMIC_MEDIA,
        "disclosure_ko": DISCLOSURE_KO,
        "disclosure_en": DISCLOSURE_EN,
        "provider": provider,
        "model": model,
        "spec": spec,
        "preset": preset or {},
        "order_id": order_id,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


def xmp_packet(rec: dict) -> bytes:
    """최소 XMP 패킷. JPEG APP1 세그먼트로 삽입할 수 있다."""
    return (
        '<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/">'
        '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
        '<rdf:Description rdf:about="" '
        'xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/" '
        'xmlns:xmp="http://ns.adobe.com/xap/1.0/">'
        f'<Iptc4xmpExt:DigitalSourceType>{rec["digital_source_type"]}'
        '</Iptc4xmpExt:DigitalSourceType>'
        f'<xmp:CreatorTool>{rec["provider"]}/{rec["model"]}</xmp:CreatorTool>'
        f'<xmp:CreateDate>{rec["generated_at"]}</xmp:CreateDate>'
        '<dc:description><rdf:Alt>'
        f'<rdf:li xml:lang="ko-KR">{rec["disclosure_ko"]}</rdf:li>'
        f'<rdf:li xml:lang="x-default">{rec["disclosure_en"]}</rdf:li>'
        '</rdf:Alt></dc:description>'
        '</rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="w"?>'
    ).encode("utf-8")


def write_jpeg(path: str, bgr: np.ndarray, rec: dict, quality: int = 95) -> str:
    """AI 생성 표시를 담아 JPEG 로 저장한다."""
    import piexif

    ok, buf = cv2.imencode(".jpg", bgr, [cv2.IMWRITE_JPEG_QUALITY, quality])
    if not ok:
        raise ValueError("JPEG 인코딩 실패")
    with open(path, "wb") as fh:
        fh.write(buf.tobytes())

    exif = {
        "0th": {
            piexif.ImageIFD.ImageDescription: DISCLOSURE_EN.encode("ascii"),
            piexif.ImageIFD.Software: f"{rec['provider']}/{rec['model']}".encode(),
        },
        "Exif": {
            piexif.ExifIFD.UserComment:
                b"ASCII\x00\x00\x00" + json.dumps(rec, ensure_ascii=True).encode(),
        },
        "1st": {}, "GPS": {}, "Interop": {},
    }
    piexif.insert(piexif.dump(exif), path)
    return path


def read_disclosure(path: str) -> dict | None:
    """저장된 이미지에서 표시 레코드를 되읽는다. 감사·검증용."""
    import piexif

    try:
        exif = piexif.load(path)
        raw = exif.get("Exif", {}).get(piexif.ExifIFD.UserComment, b"")
    except Exception:
        return None
    if not raw.startswith(b"ASCII\x00\x00\x00"):
        return None
    try:
        return json.loads(raw[8:].decode("ascii"))
    except Exception:
        return None


def watermark_preview(bgr: np.ndarray, text: str = "AI 생성 · 미리보기",
                      opacity: float = 0.55) -> np.ndarray:
    """프리뷰용 가시 워터마크. 유료 산출물에는 적용하지 않는다.

    OpenCV 의 기본 폰트는 한글을 렌더링하지 못하므로, 한글이 섞이면
    ASCII 문구로 대체한다. 프로덕션에서는 PIL + 한글 폰트를 쓸 것.
    """
    out = bgr.copy()
    h, w = out.shape[:2]
    if not text.isascii():
        text = "AI GENERATED - PREVIEW"

    scale = w / 620.0
    thick = max(1, int(round(scale * 1.6)))
    (tw, th), _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, scale, thick)
    x, y = (w - tw) // 2, h - max(10, int(h * 0.045))

    band = out[max(0, y - th - 8):min(h, y + 10), :]
    if band.size:
        band[:] = cv2.addWeighted(band, 1 - opacity * 0.5,
                                  np.zeros_like(band), opacity * 0.5, 0)
    cv2.putText(out, text, (x, y), cv2.FONT_HERSHEY_SIMPLEX, scale,
                (255, 255, 255), thick, cv2.LINE_AA)
    return out
